const Product = require('../models/product');

const createProduct = async (req, res) => {
    const { productName, description, price, imageVideo, category } = req.body;

    try {
        if (!productName || !description || !price || !imageVideo || !category) {
            return res.status(400).json({ status: 'error', message: 'Missing Required Fields!' });
        }

        // Validate the price
        if (isNaN(price) || price <= 0) {
            return res.status(400).json({ status: 'error', message: 'Price must be a positive number' });
        }

        // Check if product already exists
        const existingProduct = await Product.findOne({ where: { productName } });
        if (existingProduct) {
            return res.status(400).json({ status: 'error', message: 'Product already exists!' });
        }

        // Create new product (productId is auto-generated by Sequelize)
        const newProduct = await Product.create({
            productName,
            description,
            price,
            imageVideo,
            category,
        });

        res.status(201).json({
            status: 'success',
            message: 'Product Added Successfully!',
            product: {
                id: newProduct.productId, // Auto-generated primary key
                name: newProduct.productName,
                description: newProduct.description,
                price: newProduct.price,
                imageVideo: newProduct.imageVideo,
                category: newProduct.category
            }
        });
    } catch (err) {
        console.error('Error Adding Product:', err);
        res.status(500).json({ status: 'error', message: 'Internal Server Error' });
    }
};

module.exports = createProduct;
